version: '3.8'

services:
  # ============================================
  # DATABASES
  # ============================================
  postgres:
    image: postgres:15-alpine
    container_name: borgos-postgres
    environment:
      - POSTGRES_USER=borgos
      - POSTGRES_PASSWORD=${DB_PASSWORD:-borgos123}
      - POSTGRES_DB=borgos
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - borgos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U borgos"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: borgos-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - borgos-network
    restart: unless-stopped

  # ============================================
  # AI - OLLAMA
  # ============================================
  ollama:
    image: ollama/ollama:latest
    container_name: borgos-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - borgos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4G

  # ============================================
  # WEB UI
  # ============================================
  webui:
    image: nginx:alpine
    container_name: borgos-webui
    ports:
      - "80:80"
    volumes:
      - ./webui:/usr/share/nginx/html:ro
    networks:
      - borgos-network
    restart: unless-stopped

  # ============================================
  # DEVOPS TOOLS (OPTIONAL)
  # ============================================
  portainer:
    image: portainer/portainer-ce:latest
    container_name: borgos-portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - borgos-network
    restart: unless-stopped

networks:
  borgos-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  ollama-data:
  portainer-data: