apiVersion: apps/v1
kind: Deployment
metadata:
  name: borgos-website
  namespace: borgos
  labels:
    app: borgos-website
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: borgos-website
  template:
    metadata:
      labels:
        app: borgos-website
        component: frontend
    spec:
      containers:
      - name: website
        image: borgos/website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: borgos-website-service
  namespace: borgos
  labels:
    app: borgos-website
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: borgos-website