FROM --platform=linux/amd64 debian:12

RUN apt-get update && apt-get install -y \
    qemu-system-x86 \
    qemu-utils \
    novnc \
    websockify \
    supervisor \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

# VNC setup
RUN mkdir -p /var/log/supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 5900 6080 22 6969

CMD ["/usr/bin/supervisord"]
